# Generated by Django 3.0.2 on 2020-12-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201204_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='service',
            name='phone',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='stuff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Stuff'),
        ),
    ]
