# Generated by Django 3.0.2 on 2020-12-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20201204_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Appointment',
        ),
    ]
