# Generated by Django 4.1.6 on 2023-05-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_auto_20201204_1800"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="service",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="stuff",
        ),
        migrations.AddField(
            model_name="appointment",
            name="neme",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="programmer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.programmer",
            ),
        ),
        migrations.AlterField(
            model_name="programmer",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
