# Generated by Django 4.1.6 on 2023-05-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_servises"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Servises",
            new_name="Servise",
        ),
    ]
