# Generated by Django 4.1.6 on 2023-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_rename_servises_servise"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="user_profile/"),
        ),
    ]
