# Generated by Django 4.1.6 on 2023-05-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_customer_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="user_profile/"),
                ),
                ("name", models.CharField(max_length=30, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
