# Generated by Django 4.1.6 on 2023-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the Publisher.", max_length=50
                    ),
                ),
                ("website", models.URLField(help_text="The Publisher's website.")),
                (
                    "email",
                    models.EmailField(
                        help_text="The Publisher's email address.", max_length=254
                    ),
                ),
            ],
        ),
    ]
