# Generated by Django 4.1.6 on 2023-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_publisher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("proffesion", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_profile/"
                    ),
                ),
                ("f_link", models.URLField()),
                ("i_link", models.URLField()),
                ("g_link", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="publisher",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="website",
            field=models.URLField(),
        ),
    ]
