# Generated by Django 4.1.6 on 2023-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_doctor_alter_publisher_email_alter_publisher_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="article_image/"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="review",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
