# Generated by Django 4.1.6 on 2023-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_article_alter_review_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="a_link",
            field=models.URLField(null=True),
        ),
    ]
