# Generated by Django 4.1.6 on 2023-05-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Publisher",
        ),
    ]
